### ISSUE TITLE
KBM RIFT Prophecy of Ahnket

### ISSUE THREAD

**Issue by tdmeis** [kinnou02/king-molinator#13]
Seems at the bottom left where you select which version of the same you are trying to load for, IE Rift/ STL/ NMT/ PoA. The PoA button is huge and you have to find the sweet spot to be able to click to get iROTP and TD to load up.

**Comment by kinnou02** [comment]
I am not sure to understand your problem, can you post a screenshot of the interface please and also your screen resolution and ui scale configuration.
