### ISSUE TITLE
Cannot launch v 1.9.9.906

### ISSUE THREAD

**Issue by Jallenrix** [kinnou02/king-molinator#18]
I receive the following error text at logon and it doesn't stop even if I choose "Ignore":
Error: KBMReadyCheck/ReadyCheck.lua:1576: attempt to index field 'Header' (a nil value)
    In KBMReadyCheck / KBM Ready Check Synchronized Start, event Event.Addon.Load.End
stack traceback:
	[C]: in function '__index'
	KBMReadyCheck/ReadyCheck.lua:1576: in function 'ApplySettings'
	KBMReadyCheck/ReadyCheck.lua:2458: in function 'Update'
	KBMReadyCheck/ReadyCheck.lua:2473: in function 'UpdateSMode'
	KBMReadyCheck/ReadyCheck.lua:2689: in function <KBMReadyCheck/ReadyCheck.lua:2672>

**Comment by kinnou02** [comment]
Sorry about that, it seem to be related to the german translation.
I have fixed the problem for now, but i will have to find a more permanent fix later.
