### ISSUE TITLE
Eternal Weapon Buffs

### ISSUE THREAD

**Issue by jackpoz** [kinnou02/king-molinator#27]
Please implement Eternal Weapon buffs for every class in the raid ready check

List of buffs (you can edit it adding other classes:
- [x] Spirit of the Arcane (Mage)

**Comment by Rathoz** [comment]
19:18:11: [KBM] Spirit of the Shadows : B5E5E107B687FEDAA
19:18:11: [KBM] Spirit of the Wilds : B1CD787B134A73183
19:18:11: [KBM] Spirit of the Arcane : B5161AA0023BAEFD1
19:18:11: [KBM] Spirit of Arms : B0EF28442078DA6CD
19:18:11: [KBM] Spirit of Divinity : B1A7C914C6A849564

**Comment by Rathoz** [comment]
Implemented

**Comment by jackpoz** [comment]
TYVM
