### ISSUE TITLE
[TD] Malanon

### ISSUE THREAD

**Issue by kinnou02** [kinnou02/king-molinator#5]
- [ ] siphon energy cast - add summon, can happen once every minute afaik, first one should be starting at 1m
- [ ] flaming swipe timer - it's the cast that does aoe damage, probably can repeat every x seconds
- [ ] runes of power timer - probably can only happen if the boss reaches a certain percentage, maybe even x seconds after that
- [x] KBM phases, 30% phase I think is when the floor bubbles come, there is runes of power phase and add phase (initial) as well

**Comment by Zysandriel** [comment]
First syphon Energie at 30 seconds after start and 77%/78% life

**Comment by Zysandriel** [comment]
Runes of power fist time 15 seconds after reaching 60% boss life
