### ISSUE TITLE
Bastion of Steel : Translations

### ISSUE THREAD

**Issue by shapeyourbits** [kinnou02/king-molinator#54]
**Azranel:**
French:
Sticky Bomb
Magnetized

**Isiel:**
German:
Aegis of Storms
Crippling Shock

French:
Voltaic Thrust
Timed Charge
Driller Round
Heart Strike
Explosive Round
Crippling Shock

**Titan X:**
German:
Rocket Volley
Legion Pull

French:
Legion Pull
Rocket Volley
Range Module
Infection

**Comment by clowd81** [comment]
Ask and ye shall recieve

**Azranel:**
French:
Sticky Bomb - Bombe collante
Magnetized - Magnétisme

**Isiel:**
German:
Aegis of Storms - Aigis der Stürme
Crippling Shock - Lähmender Schock

French:
Voltaic Thrust - Estoc voltaïque
Timed Charge - Charge à rebours
Driller Round - Balle foreuse
Heart Strike - Frappe à cœur
Explosive Round - Balle explosive
Crippling Shock - Choc prostrant

**Titan X:**
German:
Rocket Volley - Raketensalve
Legion Pull - (Legion Pull was not found in the English strings file)

French:
Legion Pull - (Legion Pull was not found in the English strings file)
Rocket Volley - Volée de fusées
Range Module - Module de portée
Infection - Infection

**Comment by shapeyourbits** [comment]
Thanks again @clowd81 not just for giving me the translations but also for enabling me to look up things in the extracted source text, it  was extremely useful to close off these final details fixed in next version #59
