### ISSUE TITLE
Can't use the addon on prime

### ISSUE THREAD

**Issue by Akou99** [kinnou02/king-molinator#57]
Error: KingMolinator/KingMolinator.lua:3068: attempt to index field 'High' (a nil value)
    In KingMolinator / KBM Begin Init Sequence, event Event.Addon.Load.End
stack traceback:
	[C]: in function '__index'
	KingMolinator/KingMolinator.lua:3068: in function <KingMolinator/KingMolinator.lua:3064>

**Comment by shapeyourbits** [comment]
@Akou99 please try downloading the latest version and trying again, else please provide more information, such as what you were doing when this occurred, have you used KBM before, etc.

@kinnou02 I cant see where KBM.Trigger.High is derived from, do u have any idea what this was doing?

**Comment by shapeyourbits** [comment]
Ok after a bit more in-depth look it would seem to either be a race condition in rift's RunOnStartup or a failure to load Triggers.lua due an error in the addon which aborted the loading. In which case we'd need the details of the earlier error, or its mostly out of our hands. Please let us know if it happens again/reproducably!

**Comment by Akou99** [comment]
I turned all the plug-in down and it worked just fine
