### ISSUE TITLE
[NM-TD] Beligosh

### ISSUE THREAD

**Issue by Rathoz** [kinnou02/king-molinator#9]
17:49:25: [/script] {availability = "full", coordX = 684.55999755859, coordY = 1291.8599853516, coordZ = 1953.419921875, health = 1134000000, healthMax = 1134000000, id = "u800000009C00EEDB", level = 72, name = "Beligosh", nameSecondary = "Phoenix Dragon", radius = 5.25, relation = "hostile", tag = "beast", tagName = "Beast", tier = "raid", type = "U34892E205315F334"}

**Comment by kinnou02** [comment]
- Seed of Immolation - aoe debuff on players, lasts 8s, occurs every 24s starting at 24s
-  Vengeance of Beligosh - st debuff on tank, lasts 45s, occurs every 15s starting at 15s
- Magma Breath - 3s channel frontal cone, occurs every 30s starting at 30s, applies magma breath dot which lasts 13s
